### ISSUE TITLE
Users should be able to select a ski pass

### ISSUE THREAD

**Issue by ozzman84** [ozzman84/powpals-beta#49]
Will have to build out ski pass information for users so they can select them.

**Comment by notmarkmiranda** [comment]
For the short term, we could just `rails c` in and add applicable passes, but I could see a feature in the future where this could evolve to a badge on someone's profile. 

eg. `Epic Pass Local since 1999`

Maybe that's overkill and giving users the ability to select from a drop down or select "Other" and type the name of the pass. 🤷🏻‍♂️

@ozzman84, Have you considered activeadmin?

**Comment by notmarkmiranda** [comment]
- [ ] Add a model & migration for `season_pass`
name

- [ ] Add a joins table for `user_season_pass` as this seems like a many-to-many relationship
user: references
season_pass:references
